[package]
name = "olscorer_cli"
version = "0.1.0"
edition = "2021"
authors = ["Oleg Tretieu"]
description = "CLI for Olscorer"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
# CLI
clap = {version = "4.3", features = ["derive"]}

# Core
olscorer_core = {path = "../olscorer_core"}
